# This is a basic workflow to help you get started with Actions

name: Update Readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [issues]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update_readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@82b33c8
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const readme = await github.repos.getReadme({
              owner: context.repo.owner,
              repo: context.repo.repo
             });
             github.repos.createOrUpdateFileContents({
              sha: readme.data.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: readme.data.path,
              message: 'Update README',
              content: 'VGVzdCB0ZXN0',
              commiter: {
                name: 'update-readme-bot', 
                email: 'ahmedkhalaf.92@gmail.com'
              },
              author: {
                name: 'update-readme-bot',
                email: 'ahmedkhalaf.92@gmail.com' 
              }
            });
